version: '3.5'

services:
  node:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 4567:4567/tcp

  db:
    image: mongo:4.4.1-bionic
    restart: unless-stopped
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo:/data/db

volumes:
  mongo:
